### ISSUE TITLE
List of possible Errors!

### ISSUE THREAD

**Issue by flacohenao** [mathiask88/node-snap7#65]
I understand that all the errors that the client/server emits, are being reported and we can log them out.

I.E. _Connection failed. Code #665420 -  ISO : An error occurred during recv TCP : Connection timed out_

But... for being more user friendly with those errors, can you provide a list of the posible codes that we can find and what do they mean?

**Comment by mathiask88** [comment]
You can have a look into the [Snap7 ](http://snap7.sourceforge.net/) documentation, because this is a wrapper for that library. There you will find this description
![image](https://user-images.githubusercontent.com/4368785/81725651-72c0fc00-9486-11ea-9f43-c685fedefb83.png)

**ISO error codes**
https://github.com/mathiask88/node-snap7/blob/master/src/snap7.h#L181-L195
**S7Client error codes**
https://github.com/mathiask88/node-snap7/blob/master/src/snap7.h#L234-L271
**S7Server error codes**
https://github.com/mathiask88/node-snap7/blob/master/src/snap7.h#L546-L553

These codes are also populated on a client/server instance
```js
const snap7 = require('node-snap7');

const s7client = new snap7.S7Client();
console.log(s7client.errCliInvalidPlcAnswer)
```

The `ErrorText()` function demasks this error code composition and returns a textual representation of each field (S7/ISO/TCP)

**Comment by flacohenao** [comment]
Thank you!!!
